apiVersion: v1
kind: Service
metadata:
  labels:
    app: hms-ui
  name: hms-ui
spec:
  ports:
    - name: hms-ui
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: hms-ui
  type: LoadBalancer